name: "SIBEVIN'S NOTE"
markdown: redcarpet
pygments: true
encoding: UTF-8
tag_page_layout: tag_page
tag_page_dir: tag

gems:
 - jekyll-compass

excerpt_separator: "" # walk-around for the "Tag was never closed" bug
